# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda config --add channels bioconda
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyvips openslide openjpeg libtiff
    - conda activate test-environment
    - pip install -U tox-travis
    - python setup.py install

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Steven-N-Hart
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: Steven-N-Hart/dicom_wsi
    python: 3.7
