General:
    WSIFile: '../tests/CMU-1-JP2K-33005.svs'
    OutFilePrefix: output
    NumberOfLevels: 7
    OrgUIDRoot: 1.2.840.113713.15.
    WSIBrand: aperio_svs
    FrameSize: 500
    MaxFrames: 500000
    ImageFormat: .jpg      # None, .j2k, .jpg
    CompressionAmount: 90    # 0 for no compression,

BaseAttributes:
    PatientName: Bo^Jangles
    PatientBirthDate: 20000101
    PatientSex: M
    PatientID: 4f3a7f54-c23f-4d96-9a6c-35930bf6acc3
    ReferringPhysicianName: UNKNOWN^UNKNOWN
    StudyTime: 121212
    ContentTime: 121212
    AccessionNumber: UNKNOWN
    Manufacturer: aperio
    ManufacturerModelName: UNKNOWN
    DeviceSerialNumber: UNKNOWN
    SoftwareVersions: UNKNOWN
    AcquisitionDateTime: 20191229194128.000000
    ImageType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    SpecimenLabelInImage: NO
    BurnedInAnnotation: NO
    FocusMethod: AUTO
    ExtendedDepthOfField: NO
    SpecificCharacterSet: ISO_IR 100
    StudyID: Test
    StudyDate: 20191229
    SeriesDate: 20191229
    ContentDate: 20191108
    StudyTime: 194128.000000
    SeriesTime: 194128.000000
    ContentTime: 194128.000000
    Modality: SM
    VolumetricProperties: VOLUME
    PatientID: 13081967-68e1-48a2-8da5-e2844cd90e71
    StudyInstanceUID: 1.2.276.0.7230010.3.1.2.0.23267.1577648488.965861
    SeriesInstanceUID: 1.2.276.0.7230010.3.1.3.0.23267.1577648488.965862
    PatientOrientation: ''
    SamplesPerPixel: 3
    PhotometricInterpretation: RGB
    PlanarConfiguration: 0
    BitsAllocated: 8
    BitsStored: 8
    HighBit: 7
    PixelRepresentation: 0
    ImagedVolumeWidth: 15
    ImagedVolumeHeight: 15
    ImagedVolumeDepth: 1
    ImageOrientationSlide: [0, -1, 0, -1, 0, 0]
    DimensionOrganizationType: TILED_FULL
    TotalPixelMatrixFocalPlanes: 1
    NumberOfOpticalPaths: 1

