General:
    WSIFile: '../tests/CMU-1-JP2K-33005.svs'
    OutFilePrefix: output
    NumberOfLevels: 7
    OrgUIDRoot: 1.2.840.113713.15.
    WSIBrand: aperio_svs
    FrameSize: 500
    MaxFrames: 500
    ImageFormat: .jpg      # None, .j2k, .jpg
    CompressionAmount: 75    # 0 for no compression,

BaseAttributes:
    PatientName: Bo^Jangles
    PatientBirthDate: 20000101
    PatientSex: M
    ReferringPhysicianName: UNKNOWN^UNKNOWN
    StudyTime: 121212
    ContentTime: 121212
    AccessionNumber: UNKNOWN
    Manufacturer: aperio
    ManufacturerModelName: UNKNOWN
    DeviceSerialNumber: UNKNOWN
    SoftwareVersions: UNKNOWN
    AcquisitionDateTime: 20191108170224.000000
    ImageType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    SpecimenLabelInImage: NO
    BurnedInAnnotation: NO
    FocusMethod: AUTO
    ExtendedDepthOfField: NO
    SpecificCharacterSet: ISO_IR 100
    StudyID: Test
    StudyDate: 20191108
    SeriesDate: 20191108
    ContentDate: 20191108
    StudyTime: 170224.000000
    SeriesTime: 170224.000000
    ContentTime: 170224.000000
    Modality: SM
    VolumetricProperties: VOLUME
    PatientID: 13081967-68e1-48a2-8da5-e2844cd90e71
    StudyInstanceUID: None
    SeriesInstanceUID: None
    PatientOrientation: ''
    SamplesPerPixel: 3
    PhotometricInterpretation: RGB
    PlanarConfiguration: 0
    BitsAllocated: 8
    BitsStored: 8
    HighBit: 7
    PixelRepresentation: 0
    LossyImageCompression: '00'
    ImagedVolumeWidth: 15
    ImagedVolumeHeight: 15
    ImagedVolumeDepth: 1
    ImageOrientationSlide: [0, -1, 0, -1, 0, 0]
    DimensionOrganizationType: TILED_FULL
    TotalPixelMatrixFocalPlanes: 1
    NumberOfOpticalPaths: 1

