General:
    WSIFile: '../tests/CMU-1-JP2K-33005.svs'
    OutFilePrefix: output
    NumberOfLevels: 5
    OrgUIDRoot: 1.2.840.113713.15
    WSIBrand: aperio_svs
    FrameSize: 500
    ImageFormat: TIFF   #Others possible https://pillow.readthedocs.io/en/3.1.x/handbook/image-file-formats.html
    CompressionAmount: 0    # 0 for no compression, 1-9 the level of ADOBE_DEFLATE compression (for BigTIFF)
BaseAttributes:
    AcquisitionDateTime: 0000000000.000000
    BitsAllocated: 8
    BitsStored: 8
    BurnedInAnnotation: NO
    Columns: NUMBER #Calculated
    ContainerIdentifier: UNKNOWN
    DeviceSerialNumber: UNKNOWN
    DimensionOrganizationType: TILED_FULL
    ExtendedDepthOfField: NO
    FocusMethod: AUTO
    FrameOfReferenceUID: UID
    HighBit: 7
    ImagedVolumeDepth: 1
    ImagedVolumeHeight: 15
    ImagedVolumeWidth: 15
    ImageOrientationSlide: [0, -1, 0, -1, 0, 0]
    ImageType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    InstanceNumber: NUMBER #Calculated
    IssuerOfPatientID: UNKNOWN
    Manufacturer: UNKNOWN
    ManufacturerModelName: UNKNOWN
    Modality: SM
    NumberOfOpticalPaths: 1
    PatientBirthDate: 20191009
    PatientID: XXXXXXXXXXXX
    PatientName: Mr. Bo Jangles
    PatientOrientation: UNKNOWN
    PatientSex: M
    PhotometricInterpretation: RGB
    PixelData: NONE
    PixelRepresentation: 0
    PlanarConfiguration: 0
    PositionReferenceIndicator: SLIDE_CORNER
    Rows: NUMBER #Calculated
    SamplesPerPixel: 3
    SeriesDate: 20191009
    SeriesDescription: General image description
    SeriesInstanceUID: UID
    SeriesNumber: NUMBER #Calculated
    SeriesTime: 000000.000000
    SoftwareVersions: UNKNOWN
    SOPClassUID: 1.2.276.0.7230010.3.1.4.8323329.25650.1570640431.346073
    SOPInstanceUID: VL Whole Slide Microscopy Image Storage
    SpecificCharacterSet: ISO_IR 100
    SpecimenLabelInImage: NO
    StudyInstanceUID: UID
    StudyTime: 000000.000000
    TotalPixelMatrixColumns: NUMBER #Calculated
    TotalPixelMatrixRows: NUMBER #Calculated
    VolumetricProperties: VOLUME
SequenceAttributes:
    TotalPixelMatrixOriginSequence:
        XOffsetInSlideCoordinateSystem: 20
        YOffsetInSlideCoordinateSystem: 40
    IlluminationTypeCodeSequence:
        OpticalPathSequence:
            IlluminationTypeCodeSequence:
                CodingSchemeDesignator: DCM
                CodeMeaning: Brightfield illumination
                CodeValue: 111744
            OpticalPathIdentifier: 1
            OpticalPathDescription: Brightfield
            IlluminationColorCodeSequence:
                CodingSchemeDesignator: SRT
                CodeMeaning: Full Spectrum
                CodeValue: C-102C0
ConditionalAttributes:
    LossyImageCompression:
        '01':
            LossyImageCompressionRatio: 1
            LossyImageCompressionMethod: ISO_10918_1
SharedFunctionalGroupsSequence:
    PixelMeasuresSequence:
        PixelSpacing: [0.000499, 0.000499]
    InstanceNumber: NUMBER #Calculated
    ContentDate: NUMBER #Calculated
    ContentTime:  NUMBER #Calculated
    NumberofFrames: NUMBER #Calculated
    FrameType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    SliceThickness: 1
    OpticalPathIdentifier: 1
PerFrameFunctionalGroupsSequence:
    XOffsetInSlideCoordinateSystem: NUMBER #Calculated
    YOffsetInSlideCoordinateSystem: NUMBER #Calculated
    ZOffsetInSlideCoordinateSystem: NUMBER #Calculated
    DimensionIndexValues: [NUMBER, NUMBER] #Calculated
