General:
    InputFile: path/2/svs
    OutFile: output.dcm
    NumberOfLevels: 5
    OrgUIDRoot: 1.2.840.113713.15
BaseAttributes:
    AcquisitionDateTime: 0000000000.000000
    BitsAllocated: 8
    BitsStored: 8
    BurnedInAnnotation: NO
    ContainerIdentifier: UNKNOWN
    DeviceSerialNumber: UNKNOWN
    DimensionOrganizationType: TILED_FULL # Could also sparse tile to save space
    ExtendedDepthOfField: NO
    FocusMethod: AUTO
    FrameOfReferenceUID: UID
    HighBit: 7
    ImagedVolumeDepth: 1
    ImagedVolumeHeight: 15
    ImagedVolumeWidth: 15
    ImageOrientationSlide: [0, -1, 0, -1, 0, 0]
    ImageType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    IssuerOfPatientID: UNKNOWN
    Manufacturer: UNKNOWN
    ManufacturerModelName: UNKNOWN
    Modality: SM
    NumberOfOpticalPaths: 1
    PatientBirthDate: 99999999
    PatientID: XXXXXXXXXXXX
    PatientName: Mr. Bo Jangles
    PatientOrientation: UNKNOWN
    PatientSex: M
    PhotometricInterpretation: RGB
    PixelData: NONE
    PixelRepresentation: 0000H
    PlanarConfiguration: 0
    PositionReferenceIndicator: SLIDE_CORNER
    SamplesPerPixel: 3
    SeriesDate: 99999999
    SeriesDescription: General description
    SeriesInstanceUID: UID
    SeriesTime: 000000.000000
    SoftwareVersions: UNKNOWN
    SOPClassUID: 1.2.276.0.7230010.3.1.4.8323329.25650.1570640431.346073
    SOPInstanceUID: VL Whole Slide Microscopy Image Storage
    SpecificCharacterSet: ISO_IR 100
    SpecimenLabelInImage: NO
    StudyInstanceUID: UID
    StudyTime: 000000.000000
    VolumetricProperties: VOLUME

CalculatedBaseAttributes:
    Columns: NUMBER #Calculated
    InstanceNumber: NUMBER #Calculated
    Rows: NUMBER #Calculated
    SeriesNumber: NUMBER #Calculated
    TotalPixelMatrixColumns: NUMBER   #Calculated
    TotalPixelMatrixRows: NUMBER   #Calculated

SequenceAttributes:
    DimensionOrganizationSequence:
        DimensionOrganizationUID: 1.2.276.0.7230010.3.1.4.8323329.25650.1570640401.346049
    DimensionIndexSequence:
        DimensionIndexPointer: (0048, 021e)
        FunctionalGroupPointer: (0048, 021a)
    OpticalPathSequence:
        OpticalPathIdentifier: 1
        OpticalPathDescription: Brightfield
        IlluminationTypeCodeSequence:
            CodingSchemeDesignator: DCM
            CodeMeaning: Brightfield illumination
            CodeValue: 111744
        ICCProfile: RGB
    ReferencedDefinedProtocolSequence:
        ReferencedSOPClassUID: 1.2.276.0.7230010.3.1.4.8323329.25650.1570640431.346073
        ReferencedSOPInstanceUID: VL Whole Slide Microscopy Image Storage
    TotalPixelMatrixOriginSequence:
        XOffsetInSlideCoordinateSystem: 20
        YOffsetInSlideCoordinateSystem: 40

ConditionalAttributes:
    LossyImageCompression:
        '01':
            LossyImageCompressionRatio: 1
            LossyImageCompressionMethod: ISO_10918_1

SharedFunctionalGroupsSequence:
    ContentDate: NUMBER #Calculated
    ContentTime:  NUMBER #Calculated
    FrameType: [ORIGINAL, PRIMARY, VOLUME, NONE]
    InstanceNumber: NUMBER #Calculated
    NumberOfFrames: NUMBER #Calculated
    PixelMeasuresSequence:
        PixelSpacing: [0.000499, 0.000499]
    SliceThickness: 1

PerFrameFunctionalGroupsSequence:
    XOffsetInSlideCoordinateSystem: NUMBER #Calculated
    YOffsetInSlideCoordinateSystem: NUMBER #Calculated
    ZOffsetInSlideCoordinateSystem: NUMBER #Calculated
    DimensionIndexValues: [NUMBER, NUMBER] #Calculated
